//action types grouped

export const FETCH_USER = 'FETCH_USERS'
export const FETCH_USER_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USER_ERROR = 'FETCH_USERS_ERROR'

export const REFRESH_USER = 'REFRESH_USERS'
export const REFRESH_USER_SUCCESS = 'REFRESH_USERS_SUCCESS'
export const REFRESH_USER_ERROR = 'REFRESH_USERS_ERROR'

export const SHOULD_REFRESH = 'SHOULD_REFRESH'
